apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv
  labels:
    app: rebumkdb
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
