apiVersion: v1
kind: ConfigMap
metadata:
  name: rebumk-config
data:
  application.properties: |
    spring.datasource.url= jdbc:postgresql://rebumkdb:5432/rebudb
    spring.datasource.username=postgres-user
    spring.datasource.password=postgres-password
    spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
    spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.show-sql=true
    spring.jpa.hibernate.ddl-auto= update
