name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: |
        sudo docker build -t rebumk-image:latest .
        sudo docker logout
        
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: |
        sudo docker tag rebumk-image ${{ secrets.DOCKER_USERNAME }}/rebumk-image
        sudo docker push ${{ secrets.DOCKER_USERNAME }}/rebumk-image:latest
        
  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to staging
      run: sudo docker-compose -f docker-compose.yml up -d
